"""Architecture documentation generation.

TIER 2: May import from core, lib.
"""

from pathlib import Path

from arch.analyze import analyze_transitive_dependencies
from arch.visualize import generate_ascii_diagram, generate_dependency_matrix
from lib.config import get, get_project_root
from lib.docs import generate_arch_docs


def generate_architecture_md(root: Path | None = None) -> str:
    """Generate ARCHITECTURE.md with diagrams and dependency info.

    Args:
        root: Project root directory. Uses config root if not provided.

    Returns:
        Generated markdown content.
    """
    if root is None:
        root = get_project_root()

    # Get architecture data
    arch_docs = generate_arch_docs(format="full")
    ascii_diagram = generate_ascii_diagram()

    # Get dependency data
    result = analyze_transitive_dependencies(root)
    dep_matrix = generate_dependency_matrix(result["layer_dependencies"])

    # Build layer dependencies table
    layer_deps_lines = ["| Layer | Imports |", "|-------|---------|"]
    for layer, deps in sorted(result["layer_dependencies"].items()):
        deps_str = ", ".join(sorted(deps)) if deps else "-"
        layer_deps_lines.append(f"| `{layer}` | {deps_str} |")

    lines = [
        "# Architecture Documentation",
        "",
        "> Auto-generated from config.jsonc. Do not edit manually.",
        "",
        "## Overview",
        "",
        arch_docs,
        "",
        "## ASCII Diagram",
        "",
        "```",
        ascii_diagram,
        "```",
        "",
        "## Dependency Matrix",
        "",
        "```",
        dep_matrix,
        "```",
        "",
        "## Layer Dependencies",
        "",
        *layer_deps_lines,
        "",
        "## Rules",
        "",
        "1. **Dependency Rule**: Higher tiers may only import from lower tiers",
        "2. **Core Isolation**: Tier 0 has no internal dependencies (stdlib only)",
        "3. **No Circular Imports**: Enforced by layer structure",
        "",
        "## Enforcement",
        "",
        "Enable runtime layer guard in development:",
        "",
        "```python",
        "import os",
        "os.environ['DEVKIT_LAYER_GUARD'] = '1'",
        "",
        "from core.layer_guard import enable_layer_guard",
        "enable_layer_guard(strict=True)",
        "```",
        "",
        "---",
        "",
        "Generated by [devkit-plugin](https://github.com/vndredev/devkit-plugin)",
    ]

    return "\n".join(lines)


def update_architecture_md(root: Path | None = None) -> tuple[bool, str]:
    """Update docs/ARCHITECTURE.md with generated content.

    Args:
        root: Project root directory. Uses config root if not provided.

    Returns:
        Tuple of (success, message).
    """
    if root is None:
        root = get_project_root()

    docs_dir = root / "docs"
    docs_dir.mkdir(exist_ok=True)
    arch_md = docs_dir / "ARCHITECTURE.md"

    try:
        content = generate_architecture_md(root)
        arch_md.write_text(content)
        return True, f"Updated {arch_md}"
    except Exception as e:
        return False, f"Failed to update ARCHITECTURE.md: {e}"
