# Auto-generated by devkit-plugin. Do not edit manually.

## Summary
<!-- Brief description of changes (1-2 sentences) -->

## Type of Change
- [ ] Feature - New functionality
- [ ] Bug Fix - Fix for existing issue
- [ ] Refactor - Code restructuring
- [ ] Docs - Documentation only
- [ ] Chore - Maintenance/tooling

## Changes
<!-- What was changed? List the main changes -->

## Checklist (Author)
- [ ] Self-review completed
- [ ] No secrets committed
- [ ] Tests added (if needed)
- [ ] Linter passes

## Checklist (Claude Review)
- [ ] Security OK
- [ ] No Bugs Found
- [ ] Code Quality OK
- [ ] Architecture OK

## Test Plan
<!-- How was this tested? Manual tests, unit tests, etc. -->

## Related Issues
<!-- Closes #123 or Relates to #456 -->
